oc_platform_home:
    path:      /{page}
    defaults: 
        _controller: NRXPlatformBundle:Advert:index
        page :       1
    requirements :
        page : \d*
    
oc_platform_view:
    path:      /advert/{id}
    defaults:
        _controller: NRXPlatformBundle:Advert:view
    requirements:
        id:   \d+
    
oc_platform_add:
    path:      /add
    defaults: 
        _controller: NRXPlatformBundle:Advert:add

oc_platform_edit:
    path:      /edit/{id}
    defaults: 
        _controller: NRXPlatformBundle:Advert:edit
    requirements :
        id : \d+

oc_platform_delete:
    path:      /delete/{id}
    defaults: 
        _controller: NRXPlatformBundle:Advert:delete
    requirements :
        id : \d+

oc_platform_view_slug:
    path:      /{year}/{slug}.{_format}
    defaults: 
        _controller: NRXPlatformBundle:Advert:viewSlug
        _format :     html
    requirements:
        year:   \d{4}
        _format: html|xml