services:
    oc_platform.antispam:
        class: NRX\PlatformBundle\Antispam\NRXAntispam
        arguments: 
            - "@mailer"
            - %locale%
            - 50
#    nrx_platform.example:
#        class: NRX\PlatformBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
